ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS registry_digests_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS local_digests_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS storage_uri TEXT NOT NULL DEFAULT '';
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS size_bytes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS media_type TEXT NOT NULL DEFAULT '';
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS first_seen_at TIMESTAMPTZ;
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;
ALTER TABLE artifact_observations ADD COLUMN IF NOT EXISTS evidence_json TEXT NOT NULL DEFAULT '{}';
