// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analyzer_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnalyzerRunByJobID = `-- name: GetAnalyzerRunByJobID :one
SELECT id, job_id, analyzer_id, analyzer_version, ruleset_version, status, started_at, finished_at, duration_ms, input_json, output_json, error_json
FROM analyzer_runs
WHERE job_id = $1
`

func (q *Queries) GetAnalyzerRunByJobID(ctx context.Context, jobID string) (AnalyzerRun, error) {
	row := q.db.QueryRow(ctx, getAnalyzerRunByJobID, jobID)
	var i AnalyzerRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AnalyzerID,
		&i.AnalyzerVersion,
		&i.RulesetVersion,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.InputJson,
		&i.OutputJson,
		&i.ErrorJson,
	)
	return i, err
}

const insertAnalyzerRun = `-- name: InsertAnalyzerRun :one
INSERT INTO analyzer_runs (
    id,
    job_id,
    analyzer_id,
    analyzer_version,
    ruleset_version,
    status,
    started_at,
    finished_at,
    duration_ms,
    input_json,
    output_json,
    error_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) ON CONFLICT (job_id) DO UPDATE SET
    analyzer_id = EXCLUDED.analyzer_id,
    analyzer_version = EXCLUDED.analyzer_version,
    ruleset_version = EXCLUDED.ruleset_version,
    status = EXCLUDED.status,
    started_at = EXCLUDED.started_at,
    finished_at = EXCLUDED.finished_at,
    duration_ms = EXCLUDED.duration_ms,
    input_json = EXCLUDED.input_json,
    output_json = EXCLUDED.output_json,
    error_json = EXCLUDED.error_json
RETURNING id, job_id, analyzer_id, analyzer_version, ruleset_version, status, started_at, finished_at, duration_ms, input_json, output_json, error_json
`

type InsertAnalyzerRunParams struct {
	ID              string
	JobID           string
	AnalyzerID      string
	AnalyzerVersion string
	RulesetVersion  string
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	DurationMs      pgtype.Int8
	InputJson       []byte
	OutputJson      []byte
	ErrorJson       []byte
}

func (q *Queries) InsertAnalyzerRun(ctx context.Context, arg InsertAnalyzerRunParams) (AnalyzerRun, error) {
	row := q.db.QueryRow(ctx, insertAnalyzerRun,
		arg.ID,
		arg.JobID,
		arg.AnalyzerID,
		arg.AnalyzerVersion,
		arg.RulesetVersion,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.InputJson,
		arg.OutputJson,
		arg.ErrorJson,
	)
	var i AnalyzerRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AnalyzerID,
		&i.AnalyzerVersion,
		&i.RulesetVersion,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.InputJson,
		&i.OutputJson,
		&i.ErrorJson,
	)
	return i, err
}
