// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertArtifact = `-- name: InsertArtifact :one
INSERT INTO artifacts (version_id, artifact_type, filename, download_url, sha256) VALUES ($1,$2,$3,$4,$5) RETURNING id
`

type InsertArtifactParams struct {
	VersionID    pgtype.UUID
	ArtifactType string
	Filename     string
	DownloadUrl  string
	Sha256       pgtype.Text
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertArtifact,
		arg.VersionID,
		arg.ArtifactType,
		arg.Filename,
		arg.DownloadUrl,
		arg.Sha256,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
