// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertArtifact = `-- name: InsertArtifact :one
INSERT INTO artifacts (
  version_id,
  artifact_type,
  filename,
  download_url,
  sha256,
  registry_digests_json,
  local_digests_json,
  verification_status,
  storage_uri,
  size_bytes,
  media_type,
  first_seen_at,
  last_seen_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id
`

type InsertArtifactParams struct {
	VersionID           pgtype.UUID
	ArtifactType        string
	Filename            string
	DownloadUrl         string
	Sha256              pgtype.Text
	RegistryDigestsJson string
	LocalDigestsJson    string
	VerificationStatus  string
	StorageUri          string
	SizeBytes           int64
	MediaType           string
	FirstSeenAt         pgtype.Timestamptz
	LastSeenAt          pgtype.Timestamptz
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertArtifact,
		arg.VersionID,
		arg.ArtifactType,
		arg.Filename,
		arg.DownloadUrl,
		arg.Sha256,
		arg.RegistryDigestsJson,
		arg.LocalDigestsJson,
		arg.VerificationStatus,
		arg.StorageUri,
		arg.SizeBytes,
		arg.MediaType,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
