// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: correlation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSourceCorrelation = `-- name: InsertSourceCorrelation :one
INSERT INTO source_correlations (package_version_id, artifact_id, source_id, revision_id, confidence, score, conflicting_source_ids, reason, evidence_refs, explanation)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id
`

type InsertSourceCorrelationParams struct {
	PackageVersionID     pgtype.UUID
	ArtifactID           pgtype.UUID
	SourceID             pgtype.UUID
	RevisionID           pgtype.UUID
	Confidence           string
	Score                int32
	ConflictingSourceIds []byte
	Reason               string
	EvidenceRefs         []byte
	Explanation          string
}

func (q *Queries) InsertSourceCorrelation(ctx context.Context, arg InsertSourceCorrelationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertSourceCorrelation,
		arg.PackageVersionID,
		arg.ArtifactID,
		arg.SourceID,
		arg.RevisionID,
		arg.Confidence,
		arg.Score,
		arg.ConflictingSourceIds,
		arg.Reason,
		arg.EvidenceRefs,
		arg.Explanation,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listSourceCorrelationsByArtifact = `-- name: ListSourceCorrelationsByArtifact :many
SELECT id, package_version_id, artifact_id, source_id, revision_id, confidence, score, conflicting_source_ids, reason, evidence_refs, explanation, created_at
FROM source_correlations
WHERE artifact_id = $1
ORDER BY confidence, score DESC, created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListSourceCorrelationsByArtifactParams struct {
	ArtifactID pgtype.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListSourceCorrelationsByArtifact(ctx context.Context, arg ListSourceCorrelationsByArtifactParams) ([]SourceCorrelation, error) {
	rows, err := q.db.Query(ctx, listSourceCorrelationsByArtifact, arg.ArtifactID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceCorrelation
	for rows.Next() {
		var i SourceCorrelation
		if err := rows.Scan(
			&i.ID,
			&i.PackageVersionID,
			&i.ArtifactID,
			&i.SourceID,
			&i.RevisionID,
			&i.Confidence,
			&i.Score,
			&i.ConflictingSourceIds,
			&i.Reason,
			&i.EvidenceRefs,
			&i.Explanation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceCorrelationsByPackageVersion = `-- name: ListSourceCorrelationsByPackageVersion :many
SELECT id, package_version_id, artifact_id, source_id, revision_id, confidence, score, conflicting_source_ids, reason, evidence_refs, explanation, created_at
FROM source_correlations
WHERE package_version_id = $1
ORDER BY confidence, score DESC, created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListSourceCorrelationsByPackageVersionParams struct {
	PackageVersionID pgtype.UUID
	Limit            int32
	Offset           int32
}

func (q *Queries) ListSourceCorrelationsByPackageVersion(ctx context.Context, arg ListSourceCorrelationsByPackageVersionParams) ([]SourceCorrelation, error) {
	rows, err := q.db.Query(ctx, listSourceCorrelationsByPackageVersion, arg.PackageVersionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceCorrelation
	for rows.Next() {
		var i SourceCorrelation
		if err := rows.Scan(
			&i.ID,
			&i.PackageVersionID,
			&i.ArtifactID,
			&i.SourceID,
			&i.RevisionID,
			&i.Confidence,
			&i.Score,
			&i.ConflictingSourceIds,
			&i.Reason,
			&i.EvidenceRefs,
			&i.Explanation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
