// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO events_outbox (id, subject, payload) VALUES ($1,$2,$3) ON CONFLICT (id) DO NOTHING
`

type CreateOutboxEventParams struct {
	ID      string
	Subject string
	Payload []byte
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent, arg.ID, arg.Subject, arg.Payload)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE events_outbox SET status='published', published_at=now() WHERE id=$1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}
