// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: findings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFinding = `-- name: GetFinding :one
SELECT id, run_id, rule_id, rule_version, analyzer_id, analyzer_version, ecosystem, package_name, version, artifact_id, snapshot_id, category, severity_hint, confidence, title, summary, subject_json, evidence_json, tags, status, created_at, updated_at
FROM findings
WHERE id = $1
`

func (q *Queries) GetFinding(ctx context.Context, id string) (Finding, error) {
	row := q.db.QueryRow(ctx, getFinding, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RuleID,
		&i.RuleVersion,
		&i.AnalyzerID,
		&i.AnalyzerVersion,
		&i.Ecosystem,
		&i.PackageName,
		&i.Version,
		&i.ArtifactID,
		&i.SnapshotID,
		&i.Category,
		&i.SeverityHint,
		&i.Confidence,
		&i.Title,
		&i.Summary,
		&i.SubjectJson,
		&i.EvidenceJson,
		&i.Tags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFindings = `-- name: ListFindings :many
SELECT id, run_id, rule_id, rule_version, analyzer_id, analyzer_version, ecosystem, package_name, version, artifact_id, snapshot_id, category, severity_hint, confidence, title, summary, subject_json, evidence_json, tags, status, created_at, updated_at
FROM findings
WHERE ($1::text IS NULL OR ecosystem = $1)
  AND ($2::text IS NULL OR package_name = $2)
  AND ($3::text IS NULL OR version = $3)
  AND ($4::text IS NULL OR severity_hint = $4)
  AND ($5::text IS NULL OR confidence = $5)
  AND ($6::text IS NULL OR category = $6)
  AND ($7::text IS NULL OR rule_id = $7)
  AND ($8::text IS NULL OR status = $8)
  AND ($9::text IS NULL OR artifact_id = $9)
  AND ($10::text IS NULL OR snapshot_id = $10)
  AND ($11::timestamptz IS NULL OR created_at >= $11)
  AND ($12::timestamptz IS NULL OR created_at <= $12)
  AND (
    $13::timestamptz IS NULL
    OR (created_at < $13)
    OR (created_at = $13 AND id < $14)
  )
ORDER BY created_at DESC, id DESC
LIMIT $15
`

type ListFindingsParams struct {
	Ecosystem       pgtype.Text
	PackageName     pgtype.Text
	Version         pgtype.Text
	SeverityHint    pgtype.Text
	Confidence      pgtype.Text
	Category        pgtype.Text
	RuleID          pgtype.Text
	Status          pgtype.Text
	ArtifactID      pgtype.Text
	SnapshotID      pgtype.Text
	CreatedAfter    pgtype.Timestamptz
	CreatedBefore   pgtype.Timestamptz
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.Text
	Limit           int32
}

func (q *Queries) ListFindings(ctx context.Context, arg ListFindingsParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindings,
		arg.Ecosystem,
		arg.PackageName,
		arg.Version,
		arg.SeverityHint,
		arg.Confidence,
		arg.Category,
		arg.RuleID,
		arg.Status,
		arg.ArtifactID,
		arg.SnapshotID,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RuleID,
			&i.RuleVersion,
			&i.AnalyzerID,
			&i.AnalyzerVersion,
			&i.Ecosystem,
			&i.PackageName,
			&i.Version,
			&i.ArtifactID,
			&i.SnapshotID,
			&i.Category,
			&i.SeverityHint,
			&i.Confidence,
			&i.Title,
			&i.Summary,
			&i.SubjectJson,
			&i.EvidenceJson,
			&i.Tags,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFinding = `-- name: UpsertFinding :one
INSERT INTO findings (
    id,
    run_id,
    rule_id,
    rule_version,
    analyzer_id,
    analyzer_version,
    ecosystem,
    package_name,
    version,
    artifact_id,
    snapshot_id,
    category,
    severity_hint,
    confidence,
    title,
    summary,
    subject_json,
    evidence_json,
    tags,
    status,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
) ON CONFLICT (id) DO UPDATE SET
    run_id = EXCLUDED.run_id,
    rule_id = EXCLUDED.rule_id,
    rule_version = EXCLUDED.rule_version,
    analyzer_id = EXCLUDED.analyzer_id,
    analyzer_version = EXCLUDED.analyzer_version,
    ecosystem = EXCLUDED.ecosystem,
    package_name = EXCLUDED.package_name,
    version = EXCLUDED.version,
    artifact_id = EXCLUDED.artifact_id,
    snapshot_id = EXCLUDED.snapshot_id,
    category = EXCLUDED.category,
    severity_hint = EXCLUDED.severity_hint,
    confidence = EXCLUDED.confidence,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    subject_json = EXCLUDED.subject_json,
    evidence_json = EXCLUDED.evidence_json,
    tags = EXCLUDED.tags,
    updated_at = now()
RETURNING id, run_id, rule_id, rule_version, analyzer_id, analyzer_version, ecosystem, package_name, version, artifact_id, snapshot_id, category, severity_hint, confidence, title, summary, subject_json, evidence_json, tags, status, created_at, updated_at
`

type UpsertFindingParams struct {
	ID              string
	RunID           string
	RuleID          string
	RuleVersion     string
	AnalyzerID      string
	AnalyzerVersion string
	Ecosystem       string
	PackageName     string
	Version         pgtype.Text
	ArtifactID      pgtype.Text
	SnapshotID      pgtype.Text
	Category        string
	SeverityHint    string
	Confidence      string
	Title           string
	Summary         string
	SubjectJson     []byte
	EvidenceJson    []byte
	Tags            []string
	Status          string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, upsertFinding,
		arg.ID,
		arg.RunID,
		arg.RuleID,
		arg.RuleVersion,
		arg.AnalyzerID,
		arg.AnalyzerVersion,
		arg.Ecosystem,
		arg.PackageName,
		arg.Version,
		arg.ArtifactID,
		arg.SnapshotID,
		arg.Category,
		arg.SeverityHint,
		arg.Confidence,
		arg.Title,
		arg.Summary,
		arg.SubjectJson,
		arg.EvidenceJson,
		arg.Tags,
		arg.Status,
		arg.CreatedAt,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RuleID,
		&i.RuleVersion,
		&i.AnalyzerID,
		&i.AnalyzerVersion,
		&i.Ecosystem,
		&i.PackageName,
		&i.Version,
		&i.ArtifactID,
		&i.SnapshotID,
		&i.Category,
		&i.SeverityHint,
		&i.Confidence,
		&i.Title,
		&i.Summary,
		&i.SubjectJson,
		&i.EvidenceJson,
		&i.Tags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
