// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graph.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishDependencyIngestionRun = `-- name: FinishDependencyIngestionRun :exec
UPDATE dependency_ingestion_runs SET finished_at = now(), edges_observed = $2 WHERE id = $1
`

type FinishDependencyIngestionRunParams struct {
	ID            pgtype.UUID
	EdgesObserved int32
}

func (q *Queries) FinishDependencyIngestionRun(ctx context.Context, arg FinishDependencyIngestionRunParams) error {
	_, err := q.db.Exec(ctx, finishDependencyIngestionRun, arg.ID, arg.EdgesObserved)
	return err
}

const listDependencyEdgesByChildPackageVersion = `-- name: ListDependencyEdgesByChildPackageVersion :many
SELECT id, parent_package_version_id, child_package_id, child_package_version_id, child_ecosystem, child_name_normalized, constraint_text, resolved_version, scope, relationship, is_optional, is_dev, is_build, confidence, source_type, manifest_path, lockfile_path, dependency_path, evidence_refs, edge_fingerprint, observed_at, ingestion_run_id
FROM dependency_edges
WHERE child_package_version_id = $1
ORDER BY relationship, child_ecosystem, child_name_normalized, resolved_version, edge_fingerprint
LIMIT $2 OFFSET $3
`

type ListDependencyEdgesByChildPackageVersionParams struct {
	ChildPackageVersionID pgtype.UUID
	Limit                 int32
	Offset                int32
}

func (q *Queries) ListDependencyEdgesByChildPackageVersion(ctx context.Context, arg ListDependencyEdgesByChildPackageVersionParams) ([]DependencyEdge, error) {
	rows, err := q.db.Query(ctx, listDependencyEdgesByChildPackageVersion, arg.ChildPackageVersionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DependencyEdge
	for rows.Next() {
		var i DependencyEdge
		if err := rows.Scan(
			&i.ID,
			&i.ParentPackageVersionID,
			&i.ChildPackageID,
			&i.ChildPackageVersionID,
			&i.ChildEcosystem,
			&i.ChildNameNormalized,
			&i.ConstraintText,
			&i.ResolvedVersion,
			&i.Scope,
			&i.Relationship,
			&i.IsOptional,
			&i.IsDev,
			&i.IsBuild,
			&i.Confidence,
			&i.SourceType,
			&i.ManifestPath,
			&i.LockfilePath,
			&i.DependencyPath,
			&i.EvidenceRefs,
			&i.EdgeFingerprint,
			&i.ObservedAt,
			&i.IngestionRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependencyEdgesByParent = `-- name: ListDependencyEdgesByParent :many
SELECT id, parent_package_version_id, child_package_id, child_package_version_id, child_ecosystem, child_name_normalized, constraint_text, resolved_version, scope, relationship, is_optional, is_dev, is_build, confidence, source_type, manifest_path, lockfile_path, dependency_path, evidence_refs, edge_fingerprint, observed_at, ingestion_run_id
FROM dependency_edges
WHERE parent_package_version_id = $1
ORDER BY relationship, child_ecosystem, child_name_normalized, resolved_version, edge_fingerprint
LIMIT $2 OFFSET $3
`

type ListDependencyEdgesByParentParams struct {
	ParentPackageVersionID pgtype.UUID
	Limit                  int32
	Offset                 int32
}

func (q *Queries) ListDependencyEdgesByParent(ctx context.Context, arg ListDependencyEdgesByParentParams) ([]DependencyEdge, error) {
	rows, err := q.db.Query(ctx, listDependencyEdgesByParent, arg.ParentPackageVersionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DependencyEdge
	for rows.Next() {
		var i DependencyEdge
		if err := rows.Scan(
			&i.ID,
			&i.ParentPackageVersionID,
			&i.ChildPackageID,
			&i.ChildPackageVersionID,
			&i.ChildEcosystem,
			&i.ChildNameNormalized,
			&i.ConstraintText,
			&i.ResolvedVersion,
			&i.Scope,
			&i.Relationship,
			&i.IsOptional,
			&i.IsDev,
			&i.IsBuild,
			&i.Confidence,
			&i.SourceType,
			&i.ManifestPath,
			&i.LockfilePath,
			&i.DependencyPath,
			&i.EvidenceRefs,
			&i.EdgeFingerprint,
			&i.ObservedAt,
			&i.IngestionRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageVersionStatuses = `-- name: ListPackageVersionStatuses :many
SELECT id, package_version_id, status, source_finding_id, evidence_refs, updated_at
FROM package_version_statuses
WHERE package_version_id = $1
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListPackageVersionStatuses(ctx context.Context, packageVersionID pgtype.UUID) ([]PackageVersionStatus, error) {
	rows, err := q.db.Query(ctx, listPackageVersionStatuses, packageVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PackageVersionStatus
	for rows.Next() {
		var i PackageVersionStatus
		if err := rows.Scan(
			&i.ID,
			&i.PackageVersionID,
			&i.Status,
			&i.SourceFindingID,
			&i.EvidenceRefs,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransitiveImpactStatuses = `-- name: ListTransitiveImpactStatuses :many
SELECT id, affected_package_version_id, source_package_version_id, source_status_id, source_finding_id, status, depth, impact_path, path_fingerprint, evidence_refs, created_at
FROM transitive_impact_statuses
WHERE affected_package_version_id = $1
ORDER BY depth, path_fingerprint
LIMIT $2 OFFSET $3
`

type ListTransitiveImpactStatusesParams struct {
	AffectedPackageVersionID pgtype.UUID
	Limit                    int32
	Offset                   int32
}

func (q *Queries) ListTransitiveImpactStatuses(ctx context.Context, arg ListTransitiveImpactStatusesParams) ([]TransitiveImpactStatus, error) {
	rows, err := q.db.Query(ctx, listTransitiveImpactStatuses, arg.AffectedPackageVersionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransitiveImpactStatus
	for rows.Next() {
		var i TransitiveImpactStatus
		if err := rows.Scan(
			&i.ID,
			&i.AffectedPackageVersionID,
			&i.SourcePackageVersionID,
			&i.SourceStatusID,
			&i.SourceFindingID,
			&i.Status,
			&i.Depth,
			&i.ImpactPath,
			&i.PathFingerprint,
			&i.EvidenceRefs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDependencyEdge = `-- name: UpsertDependencyEdge :one
INSERT INTO dependency_edges (parent_package_version_id, child_package_id, child_package_version_id, child_ecosystem, child_name_normalized, constraint_text, resolved_version, scope, relationship, is_optional, is_dev, is_build, confidence, source_type, manifest_path, lockfile_path, dependency_path, evidence_refs, edge_fingerprint, ingestion_run_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)
ON CONFLICT (edge_fingerprint) DO UPDATE SET evidence_refs=EXCLUDED.evidence_refs, observed_at=now(), ingestion_run_id=EXCLUDED.ingestion_run_id
RETURNING id
`

type UpsertDependencyEdgeParams struct {
	ParentPackageVersionID pgtype.UUID
	ChildPackageID         pgtype.UUID
	ChildPackageVersionID  pgtype.UUID
	ChildEcosystem         string
	ChildNameNormalized    string
	ConstraintText         string
	ResolvedVersion        string
	Scope                  string
	Relationship           string
	IsOptional             bool
	IsDev                  bool
	IsBuild                bool
	Confidence             string
	SourceType             string
	ManifestPath           string
	LockfilePath           string
	DependencyPath         []byte
	EvidenceRefs           []byte
	EdgeFingerprint        string
	IngestionRunID         pgtype.UUID
}

func (q *Queries) UpsertDependencyEdge(ctx context.Context, arg UpsertDependencyEdgeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDependencyEdge,
		arg.ParentPackageVersionID,
		arg.ChildPackageID,
		arg.ChildPackageVersionID,
		arg.ChildEcosystem,
		arg.ChildNameNormalized,
		arg.ConstraintText,
		arg.ResolvedVersion,
		arg.Scope,
		arg.Relationship,
		arg.IsOptional,
		arg.IsDev,
		arg.IsBuild,
		arg.Confidence,
		arg.SourceType,
		arg.ManifestPath,
		arg.LockfilePath,
		arg.DependencyPath,
		arg.EvidenceRefs,
		arg.EdgeFingerprint,
		arg.IngestionRunID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertDependencyIngestionRun = `-- name: UpsertDependencyIngestionRun :one
INSERT INTO dependency_ingestion_runs (source_kind, source_id, artifact_id, package_version_id, input_fingerprint, finished_at, edges_observed)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (source_kind, input_fingerprint) DO UPDATE SET finished_at=EXCLUDED.finished_at, edges_observed=EXCLUDED.edges_observed
RETURNING id
`

type UpsertDependencyIngestionRunParams struct {
	SourceKind       string
	SourceID         pgtype.UUID
	ArtifactID       pgtype.UUID
	PackageVersionID pgtype.UUID
	InputFingerprint string
	FinishedAt       pgtype.Timestamptz
	EdgesObserved    int32
}

func (q *Queries) UpsertDependencyIngestionRun(ctx context.Context, arg UpsertDependencyIngestionRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDependencyIngestionRun,
		arg.SourceKind,
		arg.SourceID,
		arg.ArtifactID,
		arg.PackageVersionID,
		arg.InputFingerprint,
		arg.FinishedAt,
		arg.EdgesObserved,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertPackageVersionStatus = `-- name: UpsertPackageVersionStatus :one
INSERT INTO package_version_statuses (package_version_id, status, source_finding_id, evidence_refs)
VALUES ($1,$2,$3,$4)
ON CONFLICT (package_version_id, status, source_finding_id) DO UPDATE SET evidence_refs=EXCLUDED.evidence_refs, updated_at=now()
RETURNING id
`

type UpsertPackageVersionStatusParams struct {
	PackageVersionID pgtype.UUID
	Status           string
	SourceFindingID  string
	EvidenceRefs     []byte
}

func (q *Queries) UpsertPackageVersionStatus(ctx context.Context, arg UpsertPackageVersionStatusParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPackageVersionStatus,
		arg.PackageVersionID,
		arg.Status,
		arg.SourceFindingID,
		arg.EvidenceRefs,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertTransitiveImpactStatus = `-- name: UpsertTransitiveImpactStatus :one
INSERT INTO transitive_impact_statuses (affected_package_version_id, source_package_version_id, source_status_id, source_finding_id, status, depth, impact_path, path_fingerprint, evidence_refs)
VALUES ($1,$2,$3,$4,'affected_by_transitive',$5,$6,$7,$8)
ON CONFLICT (affected_package_version_id, source_finding_id, path_fingerprint) DO UPDATE SET impact_path=EXCLUDED.impact_path, evidence_refs=EXCLUDED.evidence_refs
RETURNING id
`

type UpsertTransitiveImpactStatusParams struct {
	AffectedPackageVersionID pgtype.UUID
	SourcePackageVersionID   pgtype.UUID
	SourceStatusID           pgtype.UUID
	SourceFindingID          string
	Depth                    int32
	ImpactPath               []byte
	PathFingerprint          string
	EvidenceRefs             []byte
}

func (q *Queries) UpsertTransitiveImpactStatus(ctx context.Context, arg UpsertTransitiveImpactStatusParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTransitiveImpactStatus,
		arg.AffectedPackageVersionID,
		arg.SourcePackageVersionID,
		arg.SourceStatusID,
		arg.SourceFindingID,
		arg.Depth,
		arg.ImpactPath,
		arg.PathFingerprint,
		arg.EvidenceRefs,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
