// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID           string
	FindingID    pgtype.Text
	PackageName  string
	Version      string
	Severity     string
	Status       string
	Title        string
	Summary      string
	EvidenceRefs []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AnalyzerRun struct {
	ID              string
	JobID           string
	AnalyzerID      string
	AnalyzerVersion string
	RulesetVersion  string
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	DurationMs      pgtype.Int8
	InputJson       []byte
	OutputJson      []byte
	ErrorJson       []byte
}

type Artifact struct {
	ID                  pgtype.UUID
	VersionID           pgtype.UUID
	ArtifactType        string
	Filename            string
	DownloadUrl         string
	Sha256              pgtype.Text
	ObservedAt          pgtype.Timestamptz
	RegistryDigestsJson string
	LocalDigestsJson    string
	VerificationStatus  string
	StorageUri          string
	SizeBytes           int64
	MediaType           string
	FirstSeenAt         pgtype.Timestamptz
	LastSeenAt          pgtype.Timestamptz
}

type ArtifactObservation struct {
	ID           pgtype.UUID
	ArtifactID   pgtype.UUID
	Source       string
	ObservedAt   pgtype.Timestamptz
	EvidenceJson string
}

type DependencyEdge struct {
	ID                     pgtype.UUID
	ParentPackageVersionID pgtype.UUID
	ChildPackageID         pgtype.UUID
	ChildPackageVersionID  pgtype.UUID
	ChildEcosystem         string
	ChildNameNormalized    string
	ConstraintText         string
	ResolvedVersion        string
	Scope                  string
	Relationship           string
	IsOptional             bool
	IsDev                  bool
	IsBuild                bool
	Confidence             string
	SourceType             string
	ManifestPath           string
	LockfilePath           string
	DependencyPath         []byte
	EvidenceRefs           []byte
	EdgeFingerprint        string
	ObservedAt             pgtype.Timestamptz
	IngestionRunID         pgtype.UUID
}

type DependencyIngestionRun struct {
	ID               pgtype.UUID
	SourceKind       string
	SourceID         pgtype.UUID
	ArtifactID       pgtype.UUID
	PackageVersionID pgtype.UUID
	InputFingerprint string
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	EdgesObserved    int32
}

type EventsInbox struct {
	ID         string
	Subject    string
	ConsumedAt pgtype.Timestamptz
}

type EventsOutbox struct {
	ID            string
	Subject       string
	Payload       []byte
	Status        string
	RetryCount    int32
	NextAttemptAt pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
}

type Finding struct {
	ID              string
	RunID           string
	RuleID          string
	RuleVersion     string
	AnalyzerID      string
	AnalyzerVersion string
	Ecosystem       string
	PackageName     string
	Version         pgtype.Text
	ArtifactID      pgtype.Text
	SnapshotID      pgtype.Text
	Category        string
	SeverityHint    string
	Confidence      string
	Title           string
	Summary         string
	SubjectJson     []byte
	EvidenceJson    []byte
	Tags            []string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type NotificationDelivery struct {
	ID                string
	RouteID           pgtype.Text
	AlertID           pgtype.Text
	FindingID         pgtype.Text
	Channel           string
	Status            string
	Attempts          int32
	SanitizedError    string
	ProviderMessageID string
	CreatedAt         pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
}

type NotificationRoute struct {
	ID                string
	Name              string
	Channel           string
	Enabled           bool
	SeverityThreshold string
	FiltersJson       []byte
	ConfigJson        []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type OauthState struct {
	NonceHash    string
	Provider     string
	RedirectPath string
	ExpiresAt    pgtype.Timestamptz
	ConsumedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Package struct {
	ID             pgtype.UUID
	Ecosystem      string
	RegistryUrl    string
	RawName        string
	NormalizedName string
	Namespace      string
	CreatedAt      pgtype.Timestamptz
}

type PackageVersion struct {
	ID                  pgtype.UUID
	PackageID           pgtype.UUID
	RawVersion          string
	NormalizedVersion   string
	NormalizationStatus string
	CreatedAt           pgtype.Timestamptz
}

type PackageVersionStatus struct {
	ID               pgtype.UUID
	PackageVersionID pgtype.UUID
	Status           string
	SourceFindingID  string
	EvidenceRefs     []byte
	UpdatedAt        pgtype.Timestamptz
}

type ScheduledJob struct {
	ID             pgtype.UUID
	Kind           string
	Target         string
	CadenceSeconds int32
	NextRunAt      pgtype.Timestamptz
	LeaseOwner     pgtype.Text
	LeaseUntil     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type ScmRevision struct {
	ID           pgtype.UUID
	SourceID     pgtype.UUID
	Revision     string
	RevisionType string
	ObservedAt   pgtype.Timestamptz
	EvidenceRefs []byte
}

type ScmSource struct {
	ID            pgtype.UUID
	Provider      string
	ExternalID    string
	Url           string
	Owner         string
	Repo          string
	DefaultBranch string
	Visibility    string
	LastIndexedAt pgtype.Timestamptz
}

type Session struct {
	ID         string
	TokenHash  string
	UserID     pgtype.UUID
	Provider   string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

type SourceCorrelation struct {
	ID                   pgtype.UUID
	PackageVersionID     pgtype.UUID
	ArtifactID           pgtype.UUID
	SourceID             pgtype.UUID
	RevisionID           pgtype.UUID
	Confidence           string
	Score                int32
	ConflictingSourceIds []byte
	Reason               string
	EvidenceRefs         []byte
	Explanation          string
	CreatedAt            pgtype.Timestamptz
}

type SourceManifest struct {
	ID           pgtype.UUID
	SourceID     pgtype.UUID
	Path         string
	Ecosystem    string
	ManifestType string
	CommitSha    string
	ParsedAt     pgtype.Timestamptz
}

type TransitiveImpactStatus struct {
	ID                       pgtype.UUID
	AffectedPackageVersionID pgtype.UUID
	SourcePackageVersionID   pgtype.UUID
	SourceStatusID           pgtype.UUID
	SourceFindingID          string
	Status                   string
	Depth                    int32
	ImpactPath               []byte
	PathFingerprint          string
	EvidenceRefs             []byte
	CreatedAt                pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	ExternalSubject string
	CreatedAt       pgtype.Timestamptz
}

type UserCredential struct {
	UserID        pgtype.UUID
	PasswordHash  string
	HashAlgorithm string
	UpdatedAt     pgtype.Timestamptz
}

type UserIdentity struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Provider        string
	ProviderSubject string
	Username        string
	Email           string
	CreatedAt       pgtype.Timestamptz
}

type UserRole struct {
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}
