// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnalyzerRun struct {
	ID              string
	JobID           string
	AnalyzerID      string
	AnalyzerVersion string
	RulesetVersion  string
	Status          string
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	DurationMs      pgtype.Int8
	InputJson       []byte
	OutputJson      []byte
	ErrorJson       []byte
}

type Artifact struct {
	ID                  pgtype.UUID
	VersionID           pgtype.UUID
	ArtifactType        string
	Filename            string
	DownloadUrl         string
	Sha256              pgtype.Text
	ObservedAt          pgtype.Timestamptz
	RegistryDigestsJson string
	LocalDigestsJson    string
	VerificationStatus  string
	StorageUri          string
	SizeBytes           int64
	MediaType           string
	FirstSeenAt         pgtype.Timestamptz
	LastSeenAt          pgtype.Timestamptz
}

type ArtifactObservation struct {
	ID           pgtype.UUID
	ArtifactID   pgtype.UUID
	Source       string
	ObservedAt   pgtype.Timestamptz
	EvidenceJson string
}

type EventsInbox struct {
	ID         string
	Subject    string
	ConsumedAt pgtype.Timestamptz
}

type EventsOutbox struct {
	ID            string
	Subject       string
	Payload       []byte
	Status        string
	RetryCount    int32
	NextAttemptAt pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
}

type Finding struct {
	ID              string
	RunID           string
	RuleID          string
	RuleVersion     string
	AnalyzerID      string
	AnalyzerVersion string
	Ecosystem       string
	PackageName     string
	Version         pgtype.Text
	ArtifactID      pgtype.Text
	SnapshotID      pgtype.Text
	Category        string
	SeverityHint    string
	Confidence      string
	Title           string
	Summary         string
	SubjectJson     []byte
	EvidenceJson    []byte
	Tags            []string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Package struct {
	ID             pgtype.UUID
	Ecosystem      string
	RegistryUrl    string
	RawName        string
	NormalizedName string
	Namespace      string
	CreatedAt      pgtype.Timestamptz
}

type PackageVersion struct {
	ID                  pgtype.UUID
	PackageID           pgtype.UUID
	RawVersion          string
	NormalizedVersion   string
	NormalizationStatus string
	CreatedAt           pgtype.Timestamptz
}

type ScheduledJob struct {
	ID             pgtype.UUID
	Kind           string
	Target         string
	CadenceSeconds int32
	NextRunAt      pgtype.Timestamptz
	LeaseOwner     pgtype.Text
	LeaseUntil     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	ExternalSubject string
	CreatedAt       pgtype.Timestamptz
}
