// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID           pgtype.UUID
	VersionID    pgtype.UUID
	ArtifactType string
	Filename     string
	DownloadUrl  string
	Sha256       pgtype.Text
	ObservedAt   pgtype.Timestamptz
}

type ArtifactObservation struct {
	ID         pgtype.UUID
	ArtifactID pgtype.UUID
	Source     string
	ObservedAt pgtype.Timestamptz
}

type EventsInbox struct {
	ID         string
	Subject    string
	ConsumedAt pgtype.Timestamptz
}

type EventsOutbox struct {
	ID            string
	Subject       string
	Payload       []byte
	Status        string
	RetryCount    int32
	NextAttemptAt pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
}

type EvidenceRef struct {
	ID              pgtype.UUID
	FindingID       pgtype.UUID
	ArtifactID      string
	Path            string
	StartLine       pgtype.Int4
	EndLine         pgtype.Int4
	StartByte       pgtype.Int8
	EndByte         pgtype.Int8
	Hash            pgtype.Text
	ExcerptRedacted bool
}

type Finding struct {
	ID         pgtype.UUID
	StableID   string
	ArtifactID pgtype.UUID
	Severity   string
	Confidence string
	Title      string
	CreatedAt  pgtype.Timestamptz
}

type Package struct {
	ID             pgtype.UUID
	Ecosystem      string
	RegistryUrl    string
	RawName        string
	NormalizedName string
	Namespace      string
	CreatedAt      pgtype.Timestamptz
}

type PackageVersion struct {
	ID                  pgtype.UUID
	PackageID           pgtype.UUID
	RawVersion          string
	NormalizedVersion   string
	NormalizationStatus string
	CreatedAt           pgtype.Timestamptz
}

type ScheduledJob struct {
	ID             pgtype.UUID
	Kind           string
	Target         string
	CadenceSeconds int32
	NextRunAt      pgtype.Timestamptz
	LeaseOwner     pgtype.Text
	LeaseUntil     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	ExternalSubject string
	CreatedAt       pgtype.Timestamptz
}
