// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: packages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertPackage = `-- name: UpsertPackage :one
INSERT INTO packages (ecosystem, registry_url, raw_name, normalized_name, namespace) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (ecosystem, registry_url, normalized_name) DO UPDATE SET raw_name=EXCLUDED.raw_name RETURNING id
`

type UpsertPackageParams struct {
	Ecosystem      string
	RegistryUrl    string
	RawName        string
	NormalizedName string
	Namespace      string
}

func (q *Queries) UpsertPackage(ctx context.Context, arg UpsertPackageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPackage,
		arg.Ecosystem,
		arg.RegistryUrl,
		arg.RawName,
		arg.NormalizedName,
		arg.Namespace,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertPackageVersion = `-- name: UpsertPackageVersion :one
INSERT INTO package_versions (package_id, raw_version, normalized_version, normalization_status) VALUES ($1,$2,$3,$4) ON CONFLICT (package_id, normalized_version) DO UPDATE SET raw_version=EXCLUDED.raw_version RETURNING id
`

type UpsertPackageVersionParams struct {
	PackageID           pgtype.UUID
	RawVersion          string
	NormalizedVersion   string
	NormalizationStatus string
}

func (q *Queries) UpsertPackageVersion(ctx context.Context, arg UpsertPackageVersionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPackageVersion,
		arg.PackageID,
		arg.RawVersion,
		arg.NormalizedVersion,
		arg.NormalizationStatus,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
