// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"github.com/jackc/pgx/v5"
)

type Queries struct{ db DBTX }
type DBTX interface {
	Exec(context.Context, string, ...any) (pgconnCommandTag, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}
type pgconnCommandTag interface{ RowsAffected() int64 }

func New(db DBTX) *Queries { return &Queries{db: db} }
