// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduler.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueJob = `-- name: ClaimDueJob :one
UPDATE scheduled_jobs SET lease_owner=$1, lease_until=now()+($2::text || ' seconds')::interval WHERE id=(SELECT id FROM scheduled_jobs WHERE next_run_at<=now() AND (lease_until IS NULL OR lease_until<now()) ORDER BY next_run_at LIMIT 1 FOR UPDATE SKIP LOCKED) RETURNING id, kind, target, cadence_seconds, next_run_at, lease_owner, lease_until
`

type ClaimDueJobParams struct {
	LeaseOwner   pgtype.Text
	LeaseSeconds string
}

type ClaimDueJobRow struct {
	ID             pgtype.UUID
	Kind           string
	Target         string
	CadenceSeconds int32
	NextRunAt      pgtype.Timestamptz
	LeaseOwner     pgtype.Text
	LeaseUntil     pgtype.Timestamptz
}

func (q *Queries) ClaimDueJob(ctx context.Context, arg ClaimDueJobParams) (ClaimDueJobRow, error) {
	row := q.db.QueryRow(ctx, claimDueJob, arg.LeaseOwner, arg.LeaseSeconds)
	var i ClaimDueJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Target,
		&i.CadenceSeconds,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
	)
	return i, err
}

const releaseJob = `-- name: ReleaseJob :exec
UPDATE scheduled_jobs SET lease_owner=NULL, lease_until=NULL, next_run_at=$1 WHERE id=$2 AND lease_owner=$3
`

type ReleaseJobParams struct {
	NextRunAt  pgtype.Timestamptz
	ID         pgtype.UUID
	LeaseOwner pgtype.Text
}

func (q *Queries) ReleaseJob(ctx context.Context, arg ReleaseJobParams) error {
	_, err := q.db.Exec(ctx, releaseJob, arg.NextRunAt, arg.ID, arg.LeaseOwner)
	return err
}
