// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scm.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertSCMSource = `-- name: UpsertSCMSource :one
INSERT INTO scm_sources (provider, external_id, url, owner, repo, default_branch, visibility, last_indexed_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (url) DO UPDATE SET default_branch=EXCLUDED.default_branch, visibility=EXCLUDED.visibility, last_indexed_at=EXCLUDED.last_indexed_at
RETURNING id
`

type UpsertSCMSourceParams struct {
	Provider      string
	ExternalID    string
	Url           string
	Owner         string
	Repo          string
	DefaultBranch string
	Visibility    string
	LastIndexedAt pgtype.Timestamptz
}

func (q *Queries) UpsertSCMSource(ctx context.Context, arg UpsertSCMSourceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSCMSource,
		arg.Provider,
		arg.ExternalID,
		arg.Url,
		arg.Owner,
		arg.Repo,
		arg.DefaultBranch,
		arg.Visibility,
		arg.LastIndexedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
