package provider

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"time"
)

type Fake struct {
	ProviderName string
	ModelName    string
	Output       map[string]any
	Calls        int
}

func (f *Fake) Name() string {
	if f.ProviderName != "" {
		return f.ProviderName
	}
	return "fake"
}
func (f *Fake) Type() string { return "fake" }
func (f *Fake) Generate(ctx context.Context, req Request) (Response, error) {
	f.Calls++
	select {
	case <-ctx.Done():
		return Response{}, ctx.Err()
	default:
	}
	out := f.Output
	if out == nil {
		out = map[string]any{"schema_version": "v1", "verdict": "needs_review", "confidence_label": "medium", "summary": "LLM narrative over deterministic evidence; package text remains untrusted.", "attack_hypothesis": "Review suspicious deterministic evidence.", "supporting_evidence_ids": []string{}, "benign_explanations": []string{}, "recommended_actions": []string{"Review deterministic evidence in Tallow."}, "uncertainty_notes": []string{"Generated by deterministic fake provider."}, "canonical_severity_restated": "", "severity_override_attempted": false}
	}
	b, err := json.Marshal(out)
	if err != nil {
		return Response{}, err
	}
	sum := sha256.Sum256(b)
	model := f.ModelName
	if model == "" {
		model = req.Model
	}
	return Response{RequestID: req.RequestID, ProviderName: f.Name(), ProviderType: f.Type(), Model: model, OutputJSON: b, RawOutputDigest: hex.EncodeToString(sum[:]), Latency: 0 * time.Millisecond}, nil
}
